name: Release Notes

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  release-notes:
    name: Create Release Notes
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for changelog generation

    - name: Generate Release Notes
      id: release_notes
      run: |
        CURRENT_TAG=${GITHUB_REF#refs/tags/}
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -z "$PREV_TAG" ]; then
          git log --pretty=format:"- %s (%h) @%an" > CHANGELOG.md
        else
          git log --pretty=format:"- %s (%h) @%an" $PREV_TAG..$CURRENT_TAG > CHANGELOG.md
        fi
        echo "::set-output name=changelog::$(cat CHANGELOG.md)"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 